background_opacity: 0.92
colors:
  primary:
    background: '#242831'
    foreground: '#d8dee9'
  normal:
    black: '#3b4252'
    red: '#bf616a'
    green: '#a3be8c'
    yellow: '#ebcb8b'
    blue: '#81a1c1'
    magenta: '#b48ead'
    cyan: '#88c0d0'
    white: '#e5e9f0'
  bright:
    black: '#4c566a'
    red: '#bf616a'
    green: '#a3be8c'
    yellow: '#ebcb8b'
    blue: '#81a1c1'
    magenta: '#b48ead'
    cyan: '#8fbcbb'
    white: '#eceff4'
  dim:
    black: '#242831'
    red: '#94545d'
    green: '#809575'
    yellow: '#b29e75'
    blue: '#68809a'
    magenta: '#8c738c'
    cyan: '#6d96a5'
    white: '#aeb3bb'
cursor:
  style:
    blinking: Never
debug:
  render_timer: false
  persistent_logging: false
  log_level: Warn
  print_events: false
  ref_test: false
draw_bold_text_with_bright_colors: true
font:
  size: 15
  normal:
    family: SauceCodePro Nerd Font
    style: Light
  bold:
    family: SauceCodePro Nerd Font
    style: Regular
  italic:
    family: SauceCodePro Nerd Font
    style: Light Italic
  bold_italic:
    family: SauceCodePro Nerd Font
    style: Italic
  offset:
    x: 0
    y: 5
# key_bindings:
#   - { key: F, mods: Command, action: ToggleSimpleFullScreen }
mouse:
  hide_when_typing: true
# shell:
#   shell: fish
#   args:
#     - -c
#     - archey3
window:
  dynamic_padding: true
  padding:
    x: 24
    y: 24
