#
# Alacritty
#
# :: Globals
# :: Bindings
# :: Colors
# :: Cursor
# :: Debug
# :: Font
# :: Mouse
# :: Window

#
# Globals
#

background_opacity: 0.92
draw_bold_text_with_bright_colors: true

#
# Bindings
#

# key_bindings:
#   - { key: F, mods: Command, action: ToggleSimpleFullScreen }

#
# Colors
#

colors:
  primary:
    background: '#242831'
    foreground: '#d8dee9'
  normal:
    black: '#3b4252'
    red: '#bf616a'
    green: '#a3be8c'
    yellow: '#ebcb8b'
    blue: '#81a1c1'
    magenta: '#b48ead'
    cyan: '#88c0d0'
    white: '#e5e9f0'
  bright:
    black: '#4c566a' #616e88
    red: '#bf616a'
    green: '#a3be8c'
    yellow: '#ebcb8b'
    blue: '#81a1c1'
    magenta: '#b48ead'
    cyan: '#8fbcbb'
    white: '#eceff4'
  indexed_colors:
    - { index: 16, color: '#242831' }
    - { index: 17, color: '#616e88' }

#
# Cursor
#

cursor:
  style:
    blinking: Never

#
# Debug
#

debug:
  render_timer: false
  persistent_logging: false
  log_level: Warn
  print_events: false
  ref_test: false

#
# Font
#

font:
  size: 15
  normal:
    family: SauceCodePro Nerd Font
    style: Light
  bold:
    family: SauceCodePro Nerd Font
    style: Regular
  italic:
    family: SauceCodePro Nerd Font
    style: Light Italic
  bold_italic:
    family: SauceCodePro Nerd Font
    style: Italic
  offset:
    x: 0
    y: 5

#
# Mouse
#

mouse:
  hide_when_typing: true

#
# Window
#

window:
  dynamic_padding: true
  padding:
    x: 24
    y: 24
