version: '3'

services:
  web:
    build:
      context: .
    volumes:
      - ./DIRECTORY:/home/app/src
      - ~/.ssh:/home/app/.ssh
    ports:
      - "8000:8000"
    command:
      - /home/app/docker-command.sh
