function theme_gruvbox
    set -g bg 282828
    set -g bg1 3c3836
    set -g bg2 584945
    set -g bg3 665c54
    set -g bg4 7c6f64
    set -g fg ebdbb2
    set -g fg1 ebdbb2
    set -g fg2 d5c4a1
    set -g fg3 bdae93
    set -g fg4 a89984
    set -g red fb4934
    set -g green b8bb26
    set -g yellow fabd2f
    set -g blue 83a598
    set -g purple d3869b
    set -g orange fe8019
    set -g aqua 8ec07c
    set -g grey 928374

    set -g fish_color_normal $fg
    set -g fish_color_command $green
    set -g fish_color_quote $yellow
    set -g fish_color_redirection $orange
    set -g fish_color_end $orange
    set -g fish_color_error $red
    set -g fish_color_param $fg
    set -g fish_color_comment $bg3
    set -g fish_color_match $yellow
    set -g fish_color_search_match $bg
    set -g fish_color_operator $orange
    set -g fish_color_escape $orange
    set -g fish_color_cwd $bg3
    set -g fish_color_autosuggestion $bg3
    set -g fish_color_user $bg3
    set -g fish_color_host $bg3
    set -g fish_color_cancel $red
    set -g fish_pager_color_prefix $fg3
    set -g fish_pager_color_completion $fg
    set -g fish_pager_color_description $fg
    set -g fish_pager_color_progress $yellow
    set -g fish_pager_color_secondary $bg3
end
