function theme_nord
    set -g nord0 2e3440
    set -g nord1 3b4252
    set -g nord2 434c5e
    set -g nord3 4c566a
    set -g nord4 d8dee9
    set -g nord5 e5e9f0
    set -g nord6 eceff4
    set -g nord7 8fbcbb
    set -g nord8 88c0d0
    set -g nord9 81a1c1
    set -g nord10 5e81ac
    set -g nord11 bf616a
    set -g nord12 d08770
    set -g nord13 ebcb8b
    set -g nord14 a3be8c
    set -g nord15 b48ead

    set -g fish_color_normal $nord4
    set -g fish_color_command $nord14
    set -g fish_color_quote $nord13
    set -g fish_color_autosuggestion $nord3
    set -g fish_color_redirection $nord7
    set -g fish_color_end $nord4
    set -g fish_color_error $nord11
    set -g fish_color_param $nord4
    set -g fish_color_comment $nord3
    set -g fish_color_match $nord13
    set -g fish_color_search_match $nord10
    set -g fish_color_operator $nord4
    set -g fish_color_escape $nord13
    set -g fish_color_cwd $nord9
    set -g fish_color_user $nord3
    set -g fish_color_host $nord3
    set -g fish_color_cancel $nord11
    set -g fish_pager_color_prefix $nord13
    set -g fish_pager_color_completion $nord6
    set -g fish_pager_color_description $nord10
    set -g fish_pager_color_progress $nord12
    set -g fish_pager_color_secondary $nord1
end
