highlight link jsonBraces GruvboxOrange
highlight link jsonKeyword GruvboxAqua
highlight link jsonKeywordMatch GruvboxOrange
highlight link jsonNoise GruvboxOrange
highlight link jsonString GruvboxGreen
