" highlight link phpClasses GruvboxAqua
" highlight link phpDocIdentifier GruvboxBlue
" highlight link phpDocNamespaceSeparator GruvboxYellow
" highlight link phpDocParam GruvboxYellow
" highlight link phpDocTags GruvboxAqua
" highlight link phpFunctions GruvboxYellow
" highlight link phpInclude GruvboxRed
" highlight link phpMemberSelector GruvboxOrange
" highlight link phpOperator GruvboxOrange
" highlight link phpStaticClasses GruvboxAqua
